print ("-------------------------------------------")
print ("Tugas 1 SISTEM OPERASI Kelas-B")
print ("-------------------------------------------")
print ("Nama : Rangga Laksana A.")
print ("NPM : 21083010036") 
print ("-------------------------------------------")
print ("Hasil:")
print ("Halo dunia !")
print ("Ini adalah skrip Bash pertamaku di linux")
print ("------------------------------------------")
